name: Continuous Integration

on: [push, pull_request]

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry package manager
        run: |
            curl -sSL https://install.python-poetry.org | python3 -
            echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install project dependencies
        run: poetry install

      - name: Format code with Black
        run: poetry run black .

      - name: Run unit tests with Pytest
        run: poetry run pytest