name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - deploy_documentation  # Branche à surveiller pour déclencher l'action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Python et les dépendances
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install -r docs/requirements.txt  # Assurez-vous que ce fichier existe

      # Étape 3 : Générer les fichiers .rst avec sphinx-apidoc
      - name: Generate .rst files with sphinx-apidoc
        run: |
          sphinx-apidoc -o docs/source projet_kbd --force --separate

      # Étape 4 : Construire la documentation
      - name: Build documentation
        run: sphinx-build -b html -v docs/source docs/_build/html

      # Étape 5 : Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
