name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - deploy_documentation  # Branche qui déclenche le workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Poetry et les dépendances
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Poetry
        run: |
          pip install poetry
          poetry install

      # Étape 3 : Générer les fichiers .rst avec sphinx-apidoc
      - name: Generate .rst files with sphinx-apidoc
        run: |
          poetry run sphinx-apidoc -o docs/source projet_kbd --force --separate

      # Étape 4 : Construire la documentation
      - name: Build documentation
        run: poetry run sphinx-build -b html docs/source docs/_build/html

      # Étape 5 : Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
